title: On Premise Airgapped bare-metal OCP/CP4D/Watsonx.Ai
description: Offline Deployment for OCP, CP4D, and Watsonx.AI on Air-Gapped Bare-Metal Infrastructure
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  IBM: https://ibm.com
  CP4D: https://www.ibm.com/products/cloud-pak-for-data
  OpenShift:  https://www.ibm.com/cloud/openshift
  Watsonx.ai: https://watsonx.ai


logo: ibm-logo-transparent.png
favicon_ico: "https://raw.githubusercontent.com/pratiks360/onprem/refs/heads/main/ibm.ico"

color_scheme: dark
nav_enabled: true
# For copy button on code
enable_copy_code_button: true

compress_html:
  ignore:
    envs: all