title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  IBM: https://ibm.com
  CP4D: https://www.ibm.com/products/cloud-pak-for-data
  OpenShift:  https://www.ibm.com/cloud/openshift
  Watsonx.ai: https://watsonx.ai



logo: "/Users/pratiks/Documents/projects/onpremdoc/onprem/image.png"
color_scheme: dark
nav_enabled: true
# For copy button on code
enable_copy_code_button: true

